# Generated by Django 5.2.8 on 2025-11-18 18:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallpapers", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="stripe_customer_id",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="stripe_subscription_id",
        ),
        migrations.AddField(
            model_name="subscription",
            name="downloads_used",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="subscription",
            name="plan",
            field=models.CharField(
                choices=[("basic", "Basic"), ("pro", "Pro")],
                default="basic",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("cancelled", "Cancelled")],
                default="active",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[("Free", "Free"), ("basic", "Basic"), ("pro", "Pro")],
                default="Free",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="DownloadLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wallpaper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wallpapers.wallpaper",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
