# Generated by Django 5.2.8 on 2025-11-18 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallpapers", "0002_remove_subscription_stripe_customer_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="stripe_customer_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="stripe_subscription_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="plan",
            field=models.CharField(
                choices=[("basic", "Basic"), ("pro", "Pro")],
                default="basic",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="status",
            field=models.CharField(default="inactive", max_length=50),
        ),
    ]
