# Generated by Django 5.2.8 on 2025-11-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallpapers", "0003_subscription_stripe_customer_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("cancelled", "Cancelled"),
                    ("inactive", "Inactive"),
                ],
                default="inactive",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[("free", "Free"), ("basic", "Basic"), ("pro", "Pro")],
                default="free",
                max_length=10,
            ),
        ),
    ]
